# ==============================================================================
# src/api/schemas.py
# ==============================================================================
# PURPOSE:
#   Defines all Pydantic models used for API request validation and
#   response serialization. These are the data contracts between the
#   Streamlit frontend and the FastAPI backend.
#
# WHY PYDANTIC SCHEMAS MATTER:
#   FastAPI uses these models to:
#     - Automatically VALIDATE incoming request bodies (wrong type = 422 error)
#     - Automatically SERIALIZE outgoing response data to JSON
#     - Auto-generate OpenAPI (Swagger) documentation at /docs
#
#   Every API route has one request schema (what it accepts) and one
#   response schema (what it returns). This file defines all of them.
#
# NAMING CONVENTION:
#   Request bodies:  <Action>Request   (e.g., QueryRequest, UserCreateRequest)
#   Responses:       <Action>Response  (e.g., QueryResponse, UserResponse)
#   Admin actions:   <Action>Action    (e.g., ReviewAction, TokenResetAction)
#
# USED BY:
#   src/api/routes.py      (all route handlers import these)
#   src/api/main.py        (app startup uses UserCreateRequest for init admin)
# ==============================================================================

from pydantic import BaseModel, EmailStr, Field, field_validator
from typing import Optional
from datetime import datetime


# ==============================================================================
# QUERY SCHEMAS — /query endpoint
# ==============================================================================


class QueryRequest(BaseModel):
    """
    Request body for the main RAG query endpoint (POST /query).

    Fields:
        query (str):
            The user's medical question. Must be between 1 and 2000 characters.
            Example: "What are the early symptoms of type 2 diabetes?"
        session_id (str):
            UUID identifying the user's current chat session.
            Generated by the Streamlit frontend with build_session_id().
            All messages in the same session share short-term memory.
        source_filter (str, optional):
            If provided, restricts retrieval to one source type.
            Valid values: "clinical_case", "image_caption"
            Default: None (retrieve from both sources)
        top_k (int, optional):
            How many FAISS chunks to retrieve. Must be between 1 and 20.
            Default: None (uses settings.retrieval_top_k = 5)
    """

    query: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="The user's medical question",
        examples=["What are the early symptoms of type 2 diabetes?"],
    )
    session_id: str = Field(
        ...,
        min_length=36,
        max_length=36,
        description="UUID identifying the current chat session",
    )
    source_filter: Optional[str] = Field(
        default=None,
        description="Restrict retrieval to 'clinical_case' or 'image_caption'",
    )
    top_k: Optional[int] = Field(
        default=None,
        ge=1,
        le=20,
        description="Number of chunks to retrieve (1-20)",
    )

    @field_validator("source_filter")
    @classmethod
    def validate_source_filter(cls, v):
        if v is not None and v not in ("clinical_case", "image_caption"):
            raise ValueError(
                "source_filter must be 'clinical_case', 'image_caption', or null"
            )
        return v


class RetrievedChunkResponse(BaseModel):
    """
    A single retrieved context chunk returned alongside a query response.

    Purpose:
        Included in QueryResponse.retrieved_chunks so the Streamlit frontend
        can display the source evidence panel — showing users exactly which
        clinical cases or image captions backed the AI's answer.
    """

    chunk_text: str
    similarity_score: float
    source: str  # "clinical_case" or "image_caption"
    chunk_id: str
    case_id: Optional[str] = None
    patient_age: Optional[int] = None
    patient_gender: Optional[str] = None
    image_id: Optional[str] = None
    image_type: Optional[str] = None
    labels: Optional[list[str]] = None


class QueryResponse(BaseModel):
    """
    Response body for the main RAG query endpoint (POST /query).

    Fields:
        response_text (str):
            The AI-generated answer. Always includes the medical disclaimer.
        retrieved_chunks (list[RetrievedChunkResponse]):
            The context chunks that were used to generate the response.
            Empty list if the response was served from cache.
        input_tokens (int): Prompt tokens consumed (0 if cached).
        output_tokens (int): Completion tokens consumed (0 if cached).
        total_tokens (int): Total tokens consumed (0 if cached).
        served_from_cache (bool): True if response came from cache.
        was_flagged_for_review (bool): True if flagged for human review.
        risk_score (float): Risk score (0.0 to 1.0) computed by helpers.py.
        success (bool): False if the pipeline encountered a blocking error.
        error (str, optional): Error code if success is False.
    """

    response_text: str
    retrieved_chunks: list[RetrievedChunkResponse] = []
    input_tokens: int = 0
    output_tokens: int = 0
    total_tokens: int = 0
    served_from_cache: bool = False
    was_flagged_for_review: bool = False
    risk_score: float = 0.0
    success: bool = True
    error: Optional[str] = None


# ==============================================================================
# AUTH SCHEMAS — /auth endpoints
# ==============================================================================


class UserCreateRequest(BaseModel):
    """
    Request body for user registration (POST /auth/register).

    Fields:
        email (str): Valid email address. Must be unique in the database.
        password (str): Plain-text password (hashed before storage). Min 8 chars.
        full_name (str): The user's display name.
        role (str): "patient" or "admin". Default: "patient".
    """

    email: EmailStr = Field(
        ...,
        description="User's email address (must be unique)",
    )
    password: str = Field(
        ...,
        min_length=8,
        max_length=100,
        description="Password (min 8 characters)",
    )
    full_name: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="User's full display name",
    )
    role: str = Field(
        default="patient",
        description="User role: 'patient' or 'admin'",
    )

    @field_validator("role")
    @classmethod
    def validate_role(cls, v):
        if v not in ("patient", "admin"):
            raise ValueError("role must be 'patient' or 'admin'")
        return v


class LoginRequest(BaseModel):
    """
    Request body for user login (POST /auth/login).

    Fields:
        email (str): The user's registered email address.
        password (str): The user's plain-text password for verification.
    """

    email: EmailStr
    password: str = Field(..., min_length=1, max_length=100)


class TokenResponse(BaseModel):
    """
    Response body for successful authentication (POST /auth/login).

    Fields:
        access_token (str): The JWT token to include in future request headers.
        token_type (str): Always "bearer" — used in the Authorization header.
        user_id (str): The authenticated user's UUID.
        email (str): The authenticated user's email.
        role (str): The user's role ("patient" or "admin").
        full_name (str): The user's display name.
    """

    access_token: str
    token_type: str = "bearer"
    user_id: str
    email: str
    role: str
    full_name: str


class UserResponse(BaseModel):
    """
    Public representation of a user (used in admin user list responses).

    Deliberately excludes sensitive fields like hashed_password.
    """

    id: str
    email: str
    full_name: str
    role: str
    is_active: bool
    tokens_used: int
    token_limit: int
    tokens_remaining: int
    created_at: Optional[datetime] = None
    last_active_at: Optional[datetime] = None

    model_config = {"from_attributes": True}


# ==============================================================================
# ADMIN — HUMAN REVIEW SCHEMAS — /admin/review endpoints
# ==============================================================================


class ReviewQueueItemResponse(BaseModel):
    """
    A single item in the human review queue.

    Returned by GET /admin/review to list all pending flagged responses
    for healthcare professional review.
    """

    id: int
    session_id: str
    user_id: str
    user_query: str
    ai_response: str
    risk_score: float
    flag_reason: str
    status: str  # "pending", "approved", "rejected"
    reviewed_by_user_id: Optional[str] = None
    reviewer_notes: Optional[str] = None
    created_at: Optional[datetime] = None
    reviewed_at: Optional[datetime] = None

    model_config = {"from_attributes": True}


class ReviewAction(BaseModel):
    """
    Request body for submitting a review decision (POST /admin/review/{id}).

    Fields:
        action (str): "approve" or "reject".
        reviewer_notes (str, optional): Free-text notes from the reviewer.
            Example: "Response correctly described symptoms without diagnosing."
    """

    action: str = Field(
        ...,
        description="Review decision: 'approve' or 'reject'",
    )
    reviewer_notes: Optional[str] = Field(
        default=None,
        max_length=1000,
        description="Optional notes from the reviewing healthcare professional",
    )

    @field_validator("action")
    @classmethod
    def validate_action(cls, v):
        if v not in ("approve", "reject"):
            raise ValueError("action must be 'approve' or 'reject'")
        return v


# ==============================================================================
# ADMIN — TOKEN MANAGEMENT SCHEMAS — /admin/users endpoints
# ==============================================================================


class TokenResetAction(BaseModel):
    """
    Request body for resetting a user's token usage (POST /admin/users/{id}/reset-tokens).

    This action sets the user's tokens_used counter back to 0.
    The user's token_limit is not changed.
    """

    confirm: bool = Field(
        ...,
        description="Must be True to confirm the reset",
    )


class TokenLimitUpdateAction(BaseModel):
    """
    Request body for updating a user's token limit (POST /admin/users/{id}/token-limit).

    Fields:
        new_limit (int): The new token limit. Must be a positive integer.
    """

    new_limit: int = Field(
        ...,
        ge=1000,
        le=10_000_000,
        description="New token limit (1,000 to 10,000,000)",
    )


# ==============================================================================
# HEALTH CHECK SCHEMA — /health endpoint
# ==============================================================================


class HealthResponse(BaseModel):
    """
    Response body for the health check endpoint (GET /health).

    Used by Railway deployment health checks, monitoring tools, and the
    Streamlit frontend to verify the API is reachable before showing the UI.
    """

    status: str  # "healthy" or "degraded"
    app_env: str
    database: str  # "connected" or "error: <message>"
    faiss_index: str  # "loaded (N vectors)" or "not loaded"
    active_sessions: int  # Short-term memory sessions in RAM
    version: str = "1.0.0"


# ==============================================================================
# CACHE MANAGEMENT SCHEMAS — /admin/cache endpoints
# ==============================================================================


class CacheStatsResponse(BaseModel):
    """
    Response body for the cache statistics endpoint (GET /admin/cache/stats).
    """

    total_entries: int
    total_hits: int
    most_cached: list[dict]


class CacheClearResponse(BaseModel):
    """
    Response body for the cache clear endpoint (DELETE /admin/cache).
    """

    entries_cleared: int
    message: str


# ==============================================================================
# GENERIC RESPONSE SCHEMAS
# ==============================================================================


class MessageResponse(BaseModel):
    """
    Generic success/failure response used by simple action endpoints.

    Example: {"success": true, "message": "Token usage reset successfully."}
    """

    success: bool
    message: str
