# ==============================================================================
# src/memory/short_term_memory.py
# ==============================================================================
# PURPOSE:
#   Manages short-term conversational memory for active user sessions.
#   Stores the last N turns of a conversation IN MEMORY (RAM) so the
#   LLM can handle follow-up questions without losing context.
#
# WHAT IS SHORT-TERM MEMORY?
#   When a user has a multi-turn conversation like this:
#
#     User:  "I have chest pain."
#     AI:    "How long have you had the chest pain?"
#     User:  "About 3 days."
#     AI:    "Is the pain sharp or dull?"
#     User:  "It's sharp."    <- Without memory, the AI has no idea what "it" means
#
#   Short-term memory passes the previous turns to the LLM so it understands
#   that "it" refers to the chest pain from earlier in the conversation.
#
# HOW IT WORKS:
#   - Each browser session gets a unique session_id (UUID generated by frontend)
#   - This module stores a list of {"role": ..., "content": ...} dicts per session
#   - The list is stored in a Python dictionary in RAM (fast, no DB needed)
#   - When a session ends or the server restarts, memory is cleared automatically
#   - A sliding window keeps only the last N turns to control token usage
#
# IMPORTANT LIMITATION:
#   This memory lives in RAM only. If the server restarts, all short-term
#   memory is lost. This is intentional and acceptable — it mimics how
#   real chat applications handle in-session memory.
#   For persistent memory, see long_term_memory.py.
#
# THREAD SAFETY:
#   FastAPI runs with multiple worker threads. We use a threading.Lock
#   to prevent race conditions when two requests for the same session_id
#   try to read/write memory simultaneously.
#
# USED BY:
#   src/rag/pipeline.py
# ==============================================================================

import threading
from collections import defaultdict
from loguru import logger
from typing import Optional

from config.settings import settings


# ------------------------------------------------------------------------------
# MODULE-LEVEL IN-MEMORY STORE
# ------------------------------------------------------------------------------
# This dictionary holds all active session histories.
#
# Structure:
#   _session_store = {
#       "session-uuid-1": [
#           {"role": "user",      "content": "I have chest pain"},
#           {"role": "assistant", "content": "How long have you had it?"},
#           {"role": "user",      "content": "About 3 days"},
#           {"role": "assistant", "content": "Is the pain sharp or dull?"},
#       ],
#       "session-uuid-2": [...],
#   }
#
# defaultdict(list) means accessing a new session_id automatically creates
# an empty list for it — no need to check "if key not in dict" first.
# ------------------------------------------------------------------------------

_session_store: dict[str, list[dict]] = defaultdict(list)

# Stores pinned chunk_ids per session — set on Turn 1, reused on Turn 2+
_pinned_chunks_store: dict[str, list[str]] = {}

# A threading lock to prevent race conditions in multi-threaded FastAPI
_store_lock = threading.Lock()


class ShortTermMemory:
    """
    Manages the in-session conversational memory for a single application instance.

    Purpose:
        Provides a clean interface for reading and writing conversation history
        for a specific session. The pipeline.py module creates one instance of
        this class per request and uses it to load history before generation
        and save the new turn after generation.

    Design:
        This class is stateless itself — it does not hold any data.
        All data lives in the module-level _session_store dictionary.
        Multiple ShortTermMemory instances can safely share the same store
        because all access is protected by _store_lock.

    Usage in pipeline.py:
        memory = ShortTermMemory()

        # Before generation: load history for this session
        history = memory.get_history(session_id="abc-123")

        # After generation: save the new turn
        memory.add_turn(
            session_id="abc-123",
            user_message="What causes diabetes?",
            assistant_message="Diabetes is caused by...",
        )
    """

    def get_history(self, session_id: str) -> list[dict]:
        """
        Returns the conversation history for a session as a list of message dicts.

        Purpose:
            Called by pipeline.py BEFORE the generation step to inject
            previous conversation turns into the LLM prompt. This gives
            the model context about what was discussed earlier in the session.

        Parameters:
            session_id (str):
                The unique identifier for the user's current browser session.
                Generated by the Streamlit frontend when the session starts.

        Returns:
            list[dict]: A list of message dicts in OpenAI's format:
                [
                    {"role": "user",      "content": "I have chest pain"},
                    {"role": "assistant", "content": "How long have you had it?"},
                    ...
                ]
                Returns an empty list if this session has no history yet.

        Example:
            history = memory.get_history("session-uuid-123")
            print(len(history))  # 4 (2 user + 2 assistant turns)
        """
        with _store_lock:
            # Return a copy of the list so the caller cannot accidentally
            # modify the stored history by mutating the returned list
            history = list(_session_store[session_id])

        logger.debug(
            f"ShortTermMemory: loaded {len(history)} turns "
            f"for session {session_id[:8]}..."
        )

        return history

    def add_turn(
        self,
        session_id: str,
        user_message: str,
        assistant_message: str,
    ) -> None:
        """
        Adds one complete conversation turn to the session's history.

        Purpose:
            Called by pipeline.py AFTER the generation step to record
            what the user asked and what the AI replied. The next query
            in this session will include this turn in its context.

        How the sliding window works:
            After adding the new turn, if the total number of turns exceeds
            settings.short_term_memory_max_turns, the oldest turns are
            removed from the front of the list.

            Example with max_turns=3:
              Before: [turn1, turn2, turn3] (3 turns = at limit)
              Add turn4
              After:  [turn2, turn3, turn4] (turn1 removed, still 3 turns)

            Each "turn" = 2 messages (one user + one assistant).
            So max_turns=10 means 20 messages maximum in memory.

        Parameters:
            session_id (str): The session to update.
            user_message (str): What the user said in this turn.
            assistant_message (str): What the AI replied in this turn.

        Returns:
            None
        """
        with _store_lock:
            # Append the user message
            _session_store[session_id].append(
                {
                    "role": "user",
                    "content": user_message,
                }
            )

            # Append the assistant reply
            _session_store[session_id].append(
                {
                    "role": "assistant",
                    "content": assistant_message,
                }
            )

            # Apply the sliding window limit
            # Each turn = 2 messages, so max messages = max_turns * 2
            max_messages = settings.short_term_memory_max_turns * 2

            current_count = len(_session_store[session_id])

            if current_count > max_messages:
                # Remove the oldest messages from the front of the list
                # to keep total messages within the limit
                messages_to_remove = current_count - max_messages
                _session_store[session_id] = _session_store[session_id][
                    messages_to_remove:
                ]

                logger.debug(
                    f"ShortTermMemory: removed {messages_to_remove} old messages "
                    f"for session {session_id[:8]}... "
                    f"(limit: {max_messages} messages)"
                )

        logger.debug(
            f"ShortTermMemory: added 1 turn for session {session_id[:8]}... "
            f"(total turns: {len(_session_store[session_id]) // 2})"
        )

    def clear_session(self, session_id: str) -> None:
        """
        Clears all conversation history for a specific session.

        Purpose:
            Called when a user explicitly starts a new conversation
            (e.g., clicks a "New Chat" button in the Streamlit UI).
            Also useful in testing to reset state between test cases.

        Parameters:
            session_id (str): The session to clear.

        Returns:
            None
        """
        with _store_lock:
            if session_id in _session_store:
                del _session_store[session_id]
                logger.info(
                    f"ShortTermMemory: cleared history for session {session_id[:8]}..."
                )
            else:
                logger.debug(
                    f"ShortTermMemory: clear called for unknown session "
                    f"{session_id[:8]}... (nothing to clear)"
                )

    def get_turn_count(self, session_id: str) -> int:
        """
        Returns the number of complete conversation turns stored for a session.

        Purpose:
            Used by the Streamlit frontend to display how many turns are
            in the current session's memory (e.g., "Memory: 4/10 turns").

        Parameters:
            session_id (str): The session to check.

        Returns:
            int: Number of complete turns (each turn = 1 user + 1 assistant message).
                 Returns 0 if the session does not exist.

        Example:
            count = memory.get_turn_count("session-uuid-123")
            print(count)  # 3
        """
        with _store_lock:
            message_count = len(_session_store.get(session_id, []))

        # Each turn consists of 2 messages (user + assistant)
        return message_count // 2

    def get_all_active_sessions(self) -> list[str]:
        """
        Returns a list of all session IDs that currently have stored history.

        Purpose:
            Used for monitoring and debugging — lets admins see how many
            active sessions are in memory at any given time.

        Returns:
            list[str]: List of active session ID strings.
        """
        with _store_lock:
            return list(_session_store.keys())

    def get_active_session_count(self) -> int:
        """
        Returns the number of sessions currently in short-term memory.

        Purpose:
            Used by the health check endpoint to report memory usage.

        Returns:
            int: Number of sessions currently stored in RAM.
        """
        with _store_lock:
            return len(_session_store)

    def get_pinned_chunks(self, session_id: str) -> list[str]:
        """
        Returns the chunk_ids pinned from Turn 1 of this session.

        Purpose:
            On Turn 2+, the pipeline uses these IDs to re-inject the same
            source chunks that were retrieved in Turn 1, keeping follow-up
            questions anchored to the same patients/cases.

        Returns:
            list[str]: List of chunk_id strings, or [] if Turn 1 hasn't run yet.
        """
        with _store_lock:
            return list(_pinned_chunks_store.get(session_id, []))

    def set_pinned_chunks(self, session_id: str, chunk_ids: list[str]) -> None:
        """
        Stores chunk_ids from Turn 1 so future turns can re-use them.

        Purpose:
            Called by pipeline.py after the first retrieval in a session.
            Ensures follow-up questions ("what was their age?", "what imaging
            did they use?") stay anchored to the same source cases.

        Parameters:
            session_id (str): The session to pin chunks for.
            chunk_ids (list[str]): The chunk_ids returned by retrieval on Turn 1.
        """
        with _store_lock:
            _pinned_chunks_store[session_id] = chunk_ids

    def clear_session(self, session_id: str) -> None:
        """
        Clears all memory (conversation history + pinned chunks) for a session.

        Purpose:
            Called when the user starts a new conversation so old context
            doesn't bleed into the new session.
        """
        with _store_lock:
            _session_store.pop(session_id, None)
            _pinned_chunks_store.pop(session_id, None)
